update workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,11 +44,16 @@ jobs:
       - name: Generate Coverage Report in lcov Format
         run: |
           mkdir -p sonar-reports
+          PROF_DATA_PATH=$(find $(xcodebuild -workspace PowderTrackr.xcworkspace -scheme PowderTrackr -showBuildSettings | grep -m 1 OBJROOT | cut -d " " -f 3 | xargs) -name Coverage.profdata | head -n 1)
+          if [ -z "$PROF_DATA_PATH" ]; then
+            echo "Coverage.profdata not found!"
+            exit 1
+          fi
           xcrun llvm-cov export \
             -format=lcov \
-            -instr-profile $(xcodebuild -workspace PowderTrackr.xcworkspace -scheme PowderTrackr -showBuildSettings | grep -m 1 OBJROOT | cut -d " " -f 3 | xargs)/Build/Intermediates.noindex/CodeCoverage/Coverage.profdata \
-            $(xcodebuild -workspace PowderTrackr.xcworkspace -scheme PowderTrackr -showBuildSettings | grep -m 1 OBJROOT | cut -d " " -f 3 | xargs)/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/*.xctest/Contents/MacOS/* > sonar-reports/coverage.lcov
-
+            -instr-profile $PROF_DATA_PATH \
+            $(find $(xcodebuild -workspace PowderTrackr.xcworkspace -scheme PowderTrackr -showBuildSettings | grep -m 1 OBJROOT | cut -d " " -f 3 | xargs)/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator -name "*.xctest" -exec echo {}/Contents/MacOS/* \;) > sonar-reports/coverage.lcov
+          
       - name: Run SonarCloud Analysis
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
